main:
  - name: Home
    url: '/'
    weight: 10
  - name: CV
    url: 'https://drive.google.com/uc?export=download&id=1ehav_oiSY73HkeEZY9M-MKhj7OCCQbhz'
    weight: 20
  - name: Research
    url: '/project/'
    weight: 30
  - name: Publications
    url: '/publication/'
    weight: 40
  - name: Talks
    url: '/talk/'
    weight: 50
  - name: R sandbox
    url: '/post/'
    weight: 60
  - name: Contact
    url: '/#contact'
    weight: 70